import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "../components/Header";
import Head from "next/head";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>

      <Head>
        <title>2025 Jumi Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <h1>Website under constructions 🚧</h1>
      </main>
      <footer className={styles.footer}>
        <Footer/>
      </footer>
    </>
  );
}
